name: Build APK with Buildozer
on:
  workflow_dispatch: # Дозволяє запускати збірку вручну кнопкою

jobs:
  build:
    runs-on: ubuntu-22.04 # Фіксована стабільна версія Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
